version: "3.9"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    networks:
      - appnet

  core-service:
    build: ./core-service
    ports:
      - "8000:8000"
    networks:
      - appnet
    depends_on:
      - auth-service

  web:
    build: ./web
    ports:
      - "3000:80"
    networks:
      - appnet
    depends_on:
      - core-service
      - auth-service

networks:
  appnet:
    driver: bridge
