name: CI Workshop 3

on:
  push:
    paths:
      - 'Docs/Workshops/Workshop-3/**'
  pull_request:
    paths:
      - 'Docs/Workshops/Workshop-3/**'

jobs:
  auth-service:
    name: Build & Test auth-service
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Docs/Workshops/Workshop-3/auth-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        run: mvn -B -e clean install
  docker-build-auth-service:
    name: Build Docker image for auth-service
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Docs/Workshops/Workshop-3/auth-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
            docker build \
            -f Dockerfile \
            -t auth-service:latest \
            .

  

